### ISSUE TITLE
order Book dimension

### ISSUE THREAD

**Issue by excellentiam-prog** [Joaopeuko/Mql5-Python-Integration#6]
Hi Joao, greetings

Congratulations on your repository. I see that your project relied upon the MetaTrader5 python module, however, the same package lacked some flexibility. For example, with market_book_get() https://www.mql5.com/en/docs/integration/python_metatrader5/mt5marketbookget_py

we get 5 buy and 5 sell orders, as default.  How could we change the offer Book dimension?

**Comment by Joaopeuko** [comment]
Hi @excellentiam-prog,

Thank you for your kind words about the repository. As of now, there isn't a solution to change the offer Book dimension using the MetaTrader5 python module. It would indeed be amazing if such flexibility was available. I'll keep an eye on updates and possible workarounds. If I find anything, I'll surely update the repository.

Best regards
